version: 2
jobs:
  php7.3:
    docker:
      - image: circleci/php:7.3-apache-node-browsers
    working_directory: ~/php-package-template
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: composer run test

  php7.2:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/php-package-template
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: composer run test

  php7.1:
    docker:
      - image: circleci/php:7.1-apache-node-browsers
    working_directory: ~/php-package-template
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: composer run test

workflows:
  version: 2
  test:
    jobs:
      - php7.1
      - php7.2
      - php7.3
